import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { WebSocket } from 'ws';
import { generateSecretKey, getPublicKey, finalizeEvent } from 'nostr-tools/pure';
import { npubEncode } from 'nostr-tools/nip19';
const PORT = 8994, WS = `ws://127.0.0.1:${PORT}/relay`, NET='trinityone';
const K = () => { const sk = generateSecretKey(); return { sk, pub: getPublicKey(sk) }; };
const alpha = K(), beta = K();
const dir = mkdtempSync(join(tmpdir(), 'probe-'));
const relay = spawn(process.execPath, ['scripts/gateway.mjs', String(PORT)], { env: { ...process.env, TRINITY_DATA_DIR: dir, CHURCH_NPUB: [npubEncode(alpha.pub), npubEncode(beta.pub)].join(',') }, stdio: 'ignore' });
const sleep = ms => new Promise(r => setTimeout(r, ms));
for (let i = 0; i < 60; i++) { try { if ((await fetch(`http://127.0.0.1:${PORT}/status`)).ok) break; } catch {} await sleep(200); }
const ws = new WebSocket(WS); await new Promise(r => ws.on('open', r));
const pub = (evt) => new Promise(res => { const on = d => { const m = JSON.parse(d); if (m[0]==='OK' && m[1]===evt.id) { ws.off('message', on); res(m); } }; ws.on('message', on); ws.send(JSON.stringify(['EVENT', evt])); });
let t = Math.floor(Date.now()/1000);
const roster = finalizeEvent({ kind:30078, created_at: ++t, tags:[['d','trinityone/stewards:'+alpha.pub],['t',NET]], content: JSON.stringify({ pubkeys:[beta.pub], caps:{ [beta.pub]: ['care'] } }) }, alpha.sk);
console.log('roster    :', JSON.stringify(await pub(roster)).slice(0,110));
await sleep(200);
const ct = finalizeEvent({ kind:30078, created_at: ++t, tags:[['d','trinityone/careteam:'+alpha.pub],['t',NET]], content: JSON.stringify({ pubs:[] }) }, beta.sk);
console.log('careteam  :', JSON.stringify(await pub(ct)).slice(0,140));
const ctAlpha = finalizeEvent({ kind:30078, created_at: ++t, tags:[['d','trinityone/careteam:'+alpha.pub],['t',NET]], content: JSON.stringify({ pubs:[] }) }, alpha.sk);
console.log('by alpha  :', JSON.stringify(await pub(ctAlpha)).slice(0,140));
ws.close(); relay.kill(); rmSync(dir, { recursive: true, force: true });
process.exit(0);
