// help-data.jsx — TrinityOne Help content (source: help-content.md), structured for layout.
// window.HelpData. Block types: p | list | steps | do | dont | rule | note | callout
window.HelpData = {
  intro: 'Short, friendly guides for getting set up and keeping your account safe. Take your time — and ask anyone at church if you’d like a hand.',
  articles: [
    {
      id: 'welcome',
      illo: 'shield',
      title: 'How TrinityOne keeps you safe & private',
      summary: 'TrinityOne is different from most apps — in a good way.',
      minutes: 2,
      blocks: [
        { type: 'list', items: [
          { lead: 'No account, no password, no email.', text: 'There’s nothing to sign up for and nothing to forget.' },
          { lead: 'Your phone holds a private “key” that is you.', text: 'It’s made for you automatically and stays on your phone. It’s how your church knows it’s really you.' },
          { lead: 'Use your name so your church recognises you.', text: 'No phone number or email — just a friendly name your church sees. You can keep it private if you’d rather.' },
          { lead: 'No company in the middle.', text: 'Not even we can read into your account or reset it for you.' },
        ] },
        { type: 'callout', tone: 'gold', text: 'Wonderful for privacy — but it means one thing is now yours to do: a short backup. The next guide is the most important one. Please read it.' },
        { type: 'tech', text: 'Your “key” is a standard cryptographic keypair (secp256k1 — the curve Nostr and Bitcoin use). The public half is your identity (your npub); the private half signs everything you post, so it can’t be forged. There’s no server-side account — “you” is simply that keypair on your device, which is why no one, us included, can read into or reset it.' },
      ],
    },
    {
      id: 'words',
      illo: 'paper',
      title: 'Your 12 words',
      summary: 'The single most important thing. Think of them as the only key to a safe.',
      minutes: 3,
      star: true,
      blocks: [
        { type: 'p', text: 'When you set up, TrinityOne shows you 12 little words — your “recovery phrase”.' },
        { type: 'callout', tone: 'clay', text: 'As long as you have these 12 words, you can always get back into your account — even on a new phone. If you lose your phone and don’t have them written down, no one can get the account back for you. There’s no “forgot password”, because there’s no password and no company holding a copy.' },
        { type: 'steps', label: 'What to do — once', items: [
          'When the app shows your 12 words, write them on paper, in order, by hand.',
          'Keep the paper somewhere safe at home — with important documents, or a safe.',
          'Optional: write a second copy and keep it in a different safe place.',
          'Tick “I’ve saved it” in the app.',
        ] },
        { type: 'dont', items: [
          'Don’t take a photo or screenshot of them.',
          'Don’t type them into a text, email, or any website.',
          'Don’t tell anyone the words — not even someone claiming to be from the church or support.',
        ] },
        { type: 'rule', text: 'The 12 words live on paper, not on a screen — and only you have them.' },
        { type: 'tech', text: 'The 12 words are a standard BIP-39 mnemonic. They deterministically derive your private key (NIP-06), so the same words rebuild the exact same identity on any device or compatible app — there’s nothing on a server to “recover”.' },
      ],
    },
    {
      id: 'name',
      illo: 'face',
      title: 'Setting up your name & picture',
      summary: 'Be recognised in chat without giving any personal details.',
      minutes: 2,
      blocks: [
        { type: 'list', items: [
          { lead: 'Name', text: 'Tap your circle at the top, choose Display name, and type a friendly name — e.g. “Maria from Tuesday group”. Leave it blank to keep it private.' },
          { lead: 'Picture', text: 'Pick a symbol or your initial on a colour you choose. If your church turns on member photos, adults can also set a real photo — children always keep a symbol or initial, for safety. A steward can reset a photo that isn’t suitable.' },
        ] },
        { type: 'note', text: 'You can change these any time. They’re the only things others see — never your phone number, email, or real name.' },
        { type: 'callout', tone: 'sage', text: 'Some churches ask everyone to use a real first and last name so people recognise each other. If yours does, you’ll see a gentle nudge to add your surname — it stays within your church and shares no other details.' },
      ],
    },
    {
      id: 'reading',
      illo: 'book',
      title: 'Reading the Bible',
      summary: 'A whole Bible in your pocket — and it works with no signal.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'TrinityOne is a complete Bible you can read anywhere — on the bus, in the garden, in church — even with no internet at all. The first time you open it, a clear modern translation (the Berean Standard Bible) sets itself up for you. Nothing to buy, nothing to sign up for.' },
        { type: 'list', items: [
          { lead: 'Turn to any passage.', text: 'Tap the book name at the top to jump to a book and chapter.' },
          { lead: 'Make it comfy.', text: 'In the reader’s settings you can make the words bigger, and switch on tappable Strong’s word helps.' },
          { lead: 'Keep what speaks to you.', text: 'Highlight a verse, add a note, or bookmark it — these stay private on your phone.' },
        ] },
        { type: 'steps', label: 'Add another translation', items: [
          'In Read, tap the translation name at the very top (e.g. “BSB”).',
          'Tap “Browse all translations” and search — there are over a thousand, in many languages.',
          'Tap one to download it. It saves to your phone, then works offline forever after.',
        ] },
        { type: 'note', text: 'Bibles download only when you choose one, to keep the app small. Once downloaded, they’re yours offline. To switch versions, just tap the name at the top and pick.' },
        { type: 'callout', tone: 'sage', text: 'Want to find a verse? Use Search to look across every translation you’ve installed — by word or by reference.' },
        { type: 'tech', text: 'Translations are stored locally (IndexedDB) and read with a bundled WebAssembly SQLite engine, so the reader is fully offline once downloaded. Modules use open formats (MySword .bbl.mybible and USFM / Open.Bible); the 1,000+ extra translations mirror eBible.org.' },
      ],
    },
    {
      id: 'plans',
      illo: 'book',
      title: 'Reading plans & devotionals',
      summary: 'Read through the Bible with a rhythm, and catch what your church shares.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'The Plans tab helps you read with a rhythm — and it’s where the devotionals and reading plans your church shares turn up.' },
        { type: 'list', items: [
          { lead: 'Follow a plan', text: 'Browse and tap a plan to start. Each day shows your next reading; tick it off as you go. Your progress is saved on your phone.' },
          { lead: 'Devotionals from your church', text: 'When your church shares a devotional or a plan, it appears here — sometimes a few at once, sometimes one a day as they’re released.' },
          { lead: 'Keep your streak', text: 'Open the app each day to build a quiet reading streak — a gentle nudge, never a guilt-trip.' },
        ] },
        { type: 'note', text: 'Nothing here needs a sign-up — what you follow and your progress stay on your phone.' },
      ],
    },
    {
      id: 'library',
      illo: 'book',
      title: 'The Library — extras, study tools & audio',
      summary: 'More translations, study helps, and the Bible read aloud.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'The Library is where you add to your shelf — more Bible translations, study tools, and audio Bibles you can listen to. Everything downloads only when you choose it, so the app stays small and works offline once it’s on your phone.' },
        { type: 'list', items: [
          { lead: 'Audio Bibles', text: 'Download a book and listen — handy for the commute, the kitchen, or resting your eyes. A little player keeps your place.' },
          { lead: 'Study tools', text: 'Add dictionaries and word helps (like Strong’s) to dig into the original words.' },
          { lead: 'Listen & Watch', text: 'If your church links a podcast or a video channel, their talks show up under Listen and Watch.' },
        ] },
        { type: 'callout', tone: 'sage', text: 'Downloads live on your phone and don’t need a signal once they’re there. Remove anything you’re not using to free up space — you can always get it again.' },
      ],
    },
    {
      id: 'community',
      illo: 'people',
      title: 'Your church & messaging',
      summary: 'Stay connected with your church family — simply and safely.',
      minutes: 3,
      blocks: [
        { type: 'p', text: 'The Community tab is where your church life lives: announcements, group chats, and private messages. It’s a quiet, friendly space — just your church, no strangers, no adverts.' },
        { type: 'steps', label: 'Follow your church', items: [
          'Tap your circle at the top → “Follow a church”.',
          'Point your camera at the church’s QR code, or paste the link they gave you.',
          'That’s it — you’ll see their groups and announcements.',
        ] },
        { type: 'note', text: 'Some churches approve new members first. If yours does, you’ll see “Request sent — waiting for approval” — you can look around, and you’ll be able to post once a steward lets you in.' },
        { type: 'list', items: [
          { lead: 'Groups & announcements', text: 'Join in the chat, or read what the church shares. A little dot on Community tells you when something new arrives.' },
          { lead: 'Private messages', text: 'Message anyone in your church one-to-one. These are private — only you and they can read them. To keep young people safe, private messages between a child and an adult are limited to the child’s own parent and cleared youth workers.' },
          { lead: 'Share what blesses you', text: 'Send a verse, a note, or a prayer into a group with a tap.' },
          { lead: 'Prayer requests', text: 'Mark any message as a prayer request (tap 🙏) — others can see it and lift it in prayer.' },
          { lead: 'Polls', text: 'A quick poll might pop up in a group (“which date for the picnic?”). Tap an option to vote and watch the results update.' },
        ] },
        { type: 'callout', tone: 'gold', text: 'It’s a church, so do use your name — it helps people recognise and welcome you. You can stay private if you’d rather (see “Setting up your name & picture”).' },
        { type: 'p', text: 'A gentle word about that “key” you may have read about:' },
        { type: 'list', items: [
          { lead: 'You don’t manage it day to day.', text: 'The key is just how the app quietly proves it’s really you posting — there’s no password to type and nothing to log into. You simply use the app.' },
          { lead: 'Your church can’t see your private things.', text: 'Your notes stay on your phone, and your direct messages can only be read by you and the person you’re writing to.' },
          { lead: 'The one thing to keep safe is your 12 words.', text: 'They’re the backup for everything — your name and your groups. Write them on paper once and you’re covered, even on a new phone.' },
        ] },
        { type: 'callout', tone: 'sage', text: 'Not sure about the 12 words? It really is just one small thing to do once — the guide “Your 12 words” walks you through it gently, and any steward at church will happily help.' },
        { type: 'tech', text: 'Chat runs on Nostr, an open protocol: posts are signed events a relay stores and serves — you can point the app at any relay, including your church’s own. Direct messages are end-to-end encrypted (NIP-44), so the relay only ever holds ciphertext. Group membership, invite-only privacy and the safeguarding rules are enforced by the relay’s write-policy server-side, so a modified app can’t bypass them.' },
      ],
    },
    {
      id: 'serving',
      illo: 'bell',
      title: 'Serving & church events',
      summary: 'See when you’re on the rota, say if you can make events, and find the order of service.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'If you help serve at church — welcome team, worship, kids’ work — TrinityOne keeps it simple. The Serving area shows where you’re needed and lets you reply in a tap.' },
        { type: 'list', items: [
          { lead: '“You’re serving” card', text: 'When you’re on the rota, a card shows your next slot — the team, your role, the date and time. Add it to your calendar with one tap.' },
          { lead: '“Can you serve?” requests', text: 'If your church asks you to cover a slot, you’ll get a gentle request — tap Yes, Can’t this time, or ask a teammate to swap.' },
          { lead: 'Swap or step back', text: 'On a slot you’re already on, tap to ask a specific teammate to swap, or “I’m away — take me off”. Your leader is told gently, so nothing is left uncovered.' },
          { lead: 'Mark when you’re away', text: 'Going on holiday or away for a few Sundays? Mark those dates away and you won’t be put on the rota for them — no need to decline each one.' },
          { lead: 'Order of service', text: 'If there’s a run sheet for the service, an “Order of service” button on your serving card shows what’s happening, in order, and who’s leading each part (with song details for worship teams).' },
        ] },
        { type: 'p', text: 'And for everything that’s on:' },
        { type: 'list', items: [
          { lead: 'Events & socials', text: 'See what’s coming up — workdays, prayer evenings, socials. Tap an event for full details.' },
          { lead: 'Let them know you’re coming', text: 'Tap Going / Maybe / Can’t so your church can plan.' },
        ] },
        { type: 'note', text: 'You only ever see serving and events for the church you follow — nothing from anywhere else.' },
      ],
    },
    {
      id: 'care',
      illo: 'heart',
      title: 'Practical care & meal trains',
      summary: 'When someone needs a hand, the church can rally round — meals, lifts, errands, visits.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'When a family has a new baby, someone’s unwell, or a person is grieving, the church can gather round with real, practical help. If your church turns this on, you’ll see open “needs” you can sign up for — a cooked meal on Tuesday, a lift to an appointment, a bit of shopping, a friendly visit. It’s the kind of showing-up a phone message can’t do on its own.' },
        { type: 'list', items: [
          { lead: 'See what’s needed', text: 'Open needs appear in your Today screen and under the Care tab — each shows the type of help, who it’s for, and which days still need someone.' },
          { lead: 'Pick a day to help', text: 'Tap a day and tap “I’ll help”. It shows as covered so two people don’t turn up for the same slot. Changed your plans? Tap again to step back — no fuss.' },
          { lead: 'Say what you’re bringing', text: 'For meals, you can jot a quick note (“lasagne + salad”) so the family gets some variety and helpers don’t all bring the same thing.' },
        ] },
        { type: 'callout', tone: 'sage', text: 'If the help is for you, the need is yours to steer. You’ll see “This is for you”, and on any day you’re already sorted you can tap “I’m sorted” — that day comes off the list, so no one cooks a meal you don’t need.' },
        { type: 'note', text: 'Some churches keep this to a small care team rather than the whole church — either way, it’s only ever your own church, and only for as long as the help is needed.' },
      ],
    },
    {
      id: 'directory',
      illo: 'people',
      title: 'The church directory',
      summary: 'Find someone in your church and reach them — without sharing phone numbers.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'The directory is your church’s private “People” list. It’s how you find a face and a name when you want to reach someone — without anyone handing out phone numbers or email addresses.' },
        { type: 'list', items: [
          { lead: 'Find a person', text: 'In Community, open People and search by name. Tap someone to start a private, one-to-one message.' },
          { lead: 'It’s only your church', text: 'The directory shows the people in your church and no one else — no strangers, no wider internet.' },
          { lead: 'You choose what shows', text: 'Others see the name and picture you set (see “Setting up your name & picture”) — never a phone number, email, or real name you haven’t chosen to share.' },
        ] },
        { type: 'note', text: 'To keep young people safe, the same protections apply here: a child can only be messaged by their own parent and cleared youth workers (see “Children & keeping young people safe”).' },
      ],
    },
    {
      id: 'family-safety',
      illo: 'people',
      title: 'Children & keeping young people safe',
      summary: 'How your church protects under-18s — and how a parent sets up a child’s account.',
      minutes: 3,
      blocks: [
        { type: 'p', text: 'TrinityOne helps your church look after children online. Your church — not a tick-box — decides who is a child and which adults are cleared to work with young people, so the protection matches the care already taken in person. It works alongside your church’s safeguarding (background checks, policy), never instead of it.' },
        { type: 'list', items: [
          { lead: 'Children see only child-safe groups', text: 'A young person’s app shows just the groups your church has marked safe for them. Adult spaces never appear.' },
          { lead: 'Private messages are protected', text: 'A child can only be privately messaged by their own parent and by adults the church has cleared for youth work. Any other adult simply can’t.' },
          { lead: 'Your leaders are always reachable', text: 'A young person can always message the church itself if they need help.' },
        ] },
        { type: 'p', text: 'A parent can set up and look after a child’s account from their own phone:' },
        { type: 'steps', label: 'Set up your child’s account', items: [
          'Tap your circle at the top → “Children’s accounts” → “Add a child”.',
          'Enter their name. The app makes a new account and shows you its 12 recovery words — write them down and keep them safe.',
          'On your child’s phone, scan the login code to sign them in and join them to the church.',
          'A steward confirms the link — then your child is protected by the rules above.',
        ] },
        { type: 'callout', tone: 'sage', text: 'You hold your child’s 12 recovery words, so the account is yours to look after. A steward confirms every parent–child link, so no one can attach themselves to a child who isn’t theirs.' },
        { type: 'note', text: 'Not every child needs a parent account. A young person who comes to youth club can join on their own and your church will still mark and protect them — the parent link just adds a guarantee that you and your child can always reach each other.' },
        { type: 'note', text: 'This supports your church’s safeguarding — it doesn’t replace background checks, training, supervision or policy. If you’re ever concerned, speak to your church’s safeguarding lead.' },
        { type: 'tech', text: 'This is enforced at the relay, not just hidden in the app: the minor and approved-adult lists are owner-only, and the write-policy blocks child↔adult direct messages and child posts to adult groups server-side, so a tampered or third-party client can’t get around it.' },
      ],
    },
    {
      id: 'notifications',
      illo: 'bell',
      title: 'Notifications — staying in the loop',
      summary: 'Get a gentle nudge when something needs you — and choose exactly what.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'TrinityOne can let you know when there’s something for you — a message, a church announcement, or a request to serve — even when the app is closed. You’re always in control of what comes through.' },
        { type: 'steps', label: 'Turn them on or off', items: [
          'Tap your circle at the top → Settings → Notifications.',
          'Turn “Allow notifications” on (your phone may ask permission — tap Allow).',
          'Switch on only the things you’d like to hear about.',
        ] },
        { type: 'list', items: [
          { lead: 'Direct messages', text: 'When someone messages you directly. The alert never shows the message itself — just that one arrived.' },
          { lead: 'Church announcements', text: 'When your church posts in its announcements channel.' },
          { lead: 'Serving requests', text: 'When your church asks if you can serve.' },
          { lead: 'Serving reminders', text: 'A gentle reminder the evening before you’re due to serve.' },
        ] },
        { type: 'callout', tone: 'sage', text: 'On an iPhone or iPad, alerts work once TrinityOne is added to your Home Screen: tap the Share button → “Add to Home Screen”, then open it from the new icon and turn notifications on. The Notifications screen shows these steps for your device.' },
        { type: 'note', text: 'Changed your mind? Come back any time and switch things off. If your phone has blocked notifications, the app will show you a short note on how to turn them back on.' },
      ],
    },
    {
      id: 'restore',
      illo: 'phone',
      title: 'Getting a new phone',
      summary: 'This is exactly why you wrote down your 12 words.',
      minutes: 2,
      blocks: [
        { type: 'callout', tone: 'clay', text: 'Back up before you need to. The right day to save your 12 words is today — not the day your phone is lost, stolen, or broken. Open the Help screen and tap “Back up my 12 words”, write them on paper, and keep it somewhere safe. Those words are the one and only thing that brings your account — your name, your church and your groups — back.' },
        { type: 'steps', label: 'Move to a new phone', items: [
          'Install TrinityOne on the new phone.',
          'On the welcome screen, choose “Restore” (or open your identity screen → Restore).',
          'Type your 12 words in order.',
          'You’re back — same name, same groups.',
        ] },
        { type: 'note', text: 'Your 12 words bring back your account, name and groups. Your private study — notes, journals and highlights — is kept separately on the phone, so back it up too: from Settings, make a “Back up my data” file every so often and keep it somewhere safe (it’s encrypted). On the new phone, import that file to bring those across.' },
        { type: 'callout', tone: 'sage', text: 'If you don’t have the 12 words and the old phone is gone, that account can’t be recovered — you’d simply start fresh. So keep that paper safe.' },
        { type: 'tech', text: 'Restore re-derives your key from the BIP-39 words, and your identity and church follows come back off the relay. Your private study (notes, journals, highlights) lives only on the device — it isn’t on any relay — so the “Back up my data” file is a separate, encrypted export you keep yourself.' },
      ],
    },
    {
      id: 'how-it-works',
      illo: 'qr',
      title: 'How it works (the technical bit)',
      summary: 'For the curious and the technical — the open standards under the warmth.',
      minutes: 3,
      blocks: [
        { type: 'p', text: 'You never need any of this to use TrinityOne. But if you like to know how a thing really works, here it is — and it’s all open standards, nothing proprietary.' },
        { type: 'list', items: [
          { lead: 'Your identity', text: 'A secp256k1 keypair on your device (the curve Nostr and Bitcoin use). Your public key is who you are; your private key signs what you post. No server-side account exists.' },
          { lead: 'The 12 words', text: 'A BIP-39 mnemonic that derives your key (NIP-06). The same words rebuild the exact same identity anywhere — nothing is stored on a server to “recover”.' },
          { lead: 'Messaging', text: 'Nostr, an open protocol. Posts are signed events held on relays (your church can run its own). Direct messages are end-to-end encrypted (NIP-44) — relays only ever see ciphertext.' },
          { lead: 'Privacy & safeguarding', text: 'Enforced by the relay’s write-policy, not just the app: membership, invite-only groups and child↔adult message rules are checked server-side, so a modified client can’t bypass them.' },
          { lead: 'The Bible', text: 'Stored locally (IndexedDB) and read with WebAssembly SQLite — fully offline. Modules are open formats (MySword, USFM / Open.Bible).' },
          { lead: 'Open source', text: 'The whole app is AGPL-3.0 and self-hostable — a church can run its own relay on a small box and hold all of its own data.' },
        ] },
        { type: 'tech', text: 'Deeper still: the code is plain, bundler-free JSX you can read end to end, and the architecture and specs live in the project’s README and reference docs. Found a security issue? There’s a responsible-disclosure policy in SECURITY.md.' },
      ],
    },
    {
      id: 'scams',
      illo: 'noask',
      title: 'Staying safe from scams',
      summary: 'Because you’re in charge of your own key, a few simple rules keep you safe.',
      minutes: 2,
      blocks: [
        { type: 'list', items: [
          { lead: 'No one will ever need your 12 words.', text: 'The church won’t ask. We won’t ask. Support won’t ask. Anyone who asks is trying to take your account — and any money in it.' },
          { lead: 'We’ll never ask you to “verify” your words.', text: 'Any message asking you to confirm your words or key is not from us.' },
          { lead: 'If something feels off, pause.', text: 'Ask a trusted person at church before doing anything.' },
        ] },
        { type: 'rule', text: 'If in doubt: don’t share, don’t type them in. Close the app and ask someone you trust.' },
      ],
    },
    {
      id: 'console',
      illo: 'safe',
      title: 'For leaders — the steward console',
      summary: 'Run your church from a computer: members, groups, rotas, events and invites.',
      minutes: 3,
      blocks: [
        { type: 'p', text: 'If you lead or help run a church, the steward console is your behind-the-scenes desk — best opened on a computer. It’s where you welcome members, set up groups, build the serving rota, and post announcements. A first-time setup wizard walks you through naming the church and creating a few starter groups in about a minute.' },
        { type: 'list', items: [
          { lead: 'Invite people in', text: 'Share a joining code — a QR or a short code — for members to scan or type. If you prefer, approve each new member before they can post.' },
          { lead: 'Members', text: 'See who’s joined, and mark who’s a child and which adults are cleared for youth work, so the safeguarding rules apply automatically (see “Children & keeping young people safe”).' },
          { lead: 'Groups & announcements', text: 'Create chat rooms and announcement channels, set which are open or invite-only, and mark the ones that are safe for children.' },
          { lead: 'Rota', text: 'Build serving teams and schedules, send “Can you serve?” requests, and see who’s said yes, can’t, or is away.' },
          { lead: 'Events & calendar', text: 'Post events and socials and see who’s coming.' },
        ] },
        { type: 'callout', tone: 'sage', text: 'Two extra desks can be switched on in Settings when you need them: Practical care (meal trains), and Giving records — a treasurer’s ledger (see the next guide).' },
        { type: 'note', text: 'Being a steward is delegated and revocable: a steward gets their own key and can be added or removed at any time, so leadership can change hands without anyone losing access to the church.' },
        { type: 'tech', text: 'The console is the same app pointed at the church’s relay with owner/steward privileges. The relay’s write-policy is the real gatekeeper — membership, approvals, invite-only groups and the safeguarding rules are all enforced server-side, so they hold even against a modified client.' },
      ],
    },
    {
      id: 'giving-records',
      illo: 'paper',
      title: 'Giving records & statements (for treasurers)',
      summary: 'An optional, private ledger for a church’s bookkeeping — donor records, funds and year-end statements.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'A church treasurer can turn on a private Finance desk in the steward console — a simple ledger for the church’s own bookkeeping. It records gifts and other income against funds, keeps donor records, and produces printable year-end giving statements.' },
        { type: 'list', items: [
          { lead: 'A treasurer’s ledger', text: 'Record gifts (cash, bank transfer, card and so on) against funds, and export a CSV for your accounts.' },
          { lead: 'Donor records & statements', text: 'Keep a record per giver and print a year-end statement to hand out.' },
          { lead: 'UK Gift Aid (optional)', text: 'Churches that reclaim UK Gift Aid can switch on declarations, mark eligible gifts and build the claim schedule. It’s off by default and only for churches that need it.' },
        ] },
        { type: 'callout', tone: 'gold', text: 'Unlike the rest of TrinityOne, this part keeps named records on purpose — it’s your church’s books. Everything is encrypted to the church’s own key, so the relay only ever holds unreadable ciphertext and only this console can open it. Use it under your church’s privacy policy.' },
        { type: 'note', text: 'This is for the church’s records. Giving straight from your own phone wallet is a separate idea we’re still building — it isn’t live yet, so there’s nothing you need to set up for it now.' },
      ],
    },
    {
      id: 'steward',
      illo: 'qr',
      title: 'Help from a steward',
      summary: 'If setting up yourself feels daunting, you don’t have to do it alone.',
      minutes: 2,
      blocks: [
        { type: 'p', text: 'A leader or steward at your church can create an identity for you and hand it over with a simple QR code (a square barcode). You just:' },
        { type: 'steps', label: 'With a steward’s help', items: [
          'Open TrinityOne → Restore / Scan invite.',
          'Point your camera at the QR code they show you.',
          'That’s it — you’re in, no typing.',
        ] },
        { type: 'callout', tone: 'sage', text: 'They can also help you write down your 12 words, so your account is safely backed up from day one. Ask anyone at church — they’ll be glad to help.' },
      ],
    },
  ],
  card: {
    title: 'Your TrinityOne account = your 12 words',
    lines: [
      { icon: 'paper', text: 'Write them on paper, in order. Keep the paper safe at home.' },
      { icon: 'noask', text: 'Never photograph, type online, or share them.' },
      { icon: 'phone', text: 'New phone? Use the 12 words to restore.' },
      { icon: 'shield', text: 'Anyone asking for your words is a scammer. The church will never ask.' },
    ],
  },
};
