// stew-templates.jsx — on-demand printable documents, generated by the console (NOT a page/tab):
//   • the polished A4 "Join <church>" invite + key-backup sheet (wired into the Print-invite button)
//   • the devotional-series contributor template (NIP-23), opened from Resources › Devotionals
// Faithful port of the "TrinityOne Templates" design. Exposes window.TrinityTemplates.

// ── design CSS (verbatim from the handoff) — used by the print/preview popup ──
const TMPL_CSS_VARS = "--surface-2:#FBF5EA; --mono:'SF Mono',ui-monospace,'Menlo',monospace;";
const TMPL_CSS_BODY = `
  .sheet-wrap{ display:flex; justify-content:center; }
  .sheet{ width:760px; max-width:100%; background:#fff; color:#1d1810; border-radius:6px; box-shadow:var(--shadow-lg); padding:64px 64px 52px; position:relative; margin:0 auto; }
  .sheet .eyebrow{ display:flex; flex-direction:column; align-items:center; gap:11px; margin:0 0 26px; }
  .sheet .eyebrow span{ font-family:var(--font-display); font-weight:800; font-size:13px; letter-spacing:7px; color:var(--clay); }
  .sheet h1{ text-align:center; font-family:var(--font-display); font-weight:800; font-size:34px; letter-spacing:-.8px; line-height:1.1; margin:0 0 10px; }
  .sheet .lede{ text-align:center; font-family:var(--font-serif); font-size:16.5px; line-height:1.5; color:#5a5142; max-width:460px; margin:0 auto 28px; text-wrap:pretty; }
  .scan{ display:flex; flex-direction:column; align-items:center; gap:12px; padding:26px; border:1.5px solid #ece6da; border-radius:18px; margin-bottom:26px; background:#fcfaf5; }
  .scan .lab{ font-size:13px; font-weight:600; color:#6b6052; }
  .qr-box{ width:188px; height:188px; background:#fff; border-radius:12px; display:flex; align-items:center; justify-content:center; }
  .qr-box img, .qr-box svg{ width:100%; height:100%; display:block; image-rendering:pixelated; }
  .scan .url{ font-family:var(--mono); font-size:11.5px; color:#8a7f6d; word-break:break-all; text-align:center; max-width:440px; line-height:1.5; }
  .steps{ counter-reset:s; margin:0 0 24px; padding:0; list-style:none; }
  .steps li{ counter-increment:s; position:relative; padding:0 0 14px 42px; font-size:14.5px; line-height:1.5; color:#3a342a; }
  .steps li::before{ content:counter(s); position:absolute; left:0; top:-2px; width:28px; height:28px; border-radius:999px; background:var(--clay); color:#fff; font-family:var(--font-display); font-weight:800; font-size:14px; display:flex; align-items:center; justify-content:center; }
  .warn{ display:flex; gap:12px; padding:15px 17px; border-radius:14px; background:#fdf3ee; border:1px solid #f0d8cb; margin-bottom:28px; }
  .warn .ic{ flex-shrink:0; color:var(--clay); }
  .warn p{ margin:0; font-size:13px; line-height:1.55; color:#6a4a3a; }
  .warn b{ color:#4a2c1d; }
  .rec-h{ font-family:var(--font-display); font-weight:700; font-size:19px; margin:0 0 3px; }
  .rec-sub{ font-size:13px; color:#6b6052; margin:0 0 16px; }
  .grid12{ display:grid; grid-template-columns:1fr 1fr; gap:12px 18px; }
  .box{ display:flex; align-items:center; gap:11px; border:1px solid #ddd5c6; border-radius:11px; height:48px; padding:0 14px; }
  .box .n{ font-family:var(--font-display); font-weight:800; font-size:14px; color:var(--clay); width:20px; flex-shrink:0; }
  .box .line{ flex:1; border-bottom:1.5px dotted #c9bfac; height:1px; }
  .sheet .foot{ display:flex; align-items:center; justify-content:center; gap:9px; margin-top:34px; padding-top:20px; border-top:1px solid #ece6da; color:#9a8f7c; font-size:12px; font-weight:600; letter-spacing:.3px; }

  .doc{ width:820px; max-width:100%; margin:0 auto; background:var(--surface); border:1px solid var(--line); border-radius:18px; box-shadow:var(--shadow-sm); padding:46px 56px 60px; }
  .doc .top{ display:flex; align-items:flex-start; gap:16px; margin-bottom:8px; }
  .doc .pill{ display:inline-flex; align-items:center; gap:7px; font-weight:700; font-size:11px; letter-spacing:1.2px; text-transform:uppercase; padding:5px 11px; border-radius:999px; background:var(--clay-soft); color:var(--clay-ink); }
  .doc h1{ font-family:var(--font-display); font-weight:800; font-size:30px; letter-spacing:-.7px; margin:14px 0 8px; }
  .doc .sub{ font-size:15px; color:var(--ink-2); line-height:1.55; margin:0 0 8px; max-width:60ch; }
  .doc h2{ font-family:var(--font-display); font-weight:700; font-size:19px; margin:34px 0 12px; letter-spacing:-.2px; }
  .doc p{ font-size:15px; line-height:1.62; color:var(--ink); margin:0 0 12px; max-width:64ch; }
  .doc ul{ margin:0 0 14px; padding-left:20px; }
  .doc li{ font-size:15px; line-height:1.6; color:var(--ink); margin-bottom:7px; max-width:62ch; }
  .doc code{ font-family:var(--mono); font-size:13px; background:var(--surface-2); border:1px solid var(--line); border-radius:5px; padding:1px 6px; }
  .doc .rule{ display:flex; align-items:center; gap:10px; color:var(--ink-3); font-size:12px; font-weight:700; letter-spacing:.5px; text-transform:uppercase; margin:18px 0; }
  .doc .rule::before,.doc .rule::after{ content:''; flex:1; height:1px; background:var(--line); }
  .block{ background:#1c170f; color:#f3ecdc; border-radius:16px; padding:24px 26px; margin:14px 0 6px; position:relative; overflow:hidden; }
  .block pre{ margin:0; font-family:var(--mono); font-size:12.5px; line-height:1.65; white-space:pre-wrap; word-break:break-word; color:#e7ddc8; }
  .block .marker{ color:#d9ae5a; }
  .block .key{ color:#7faE8a; }
  .example{ border:1px solid var(--line); border-left:3px solid var(--clay); border-radius:0 14px 14px 0; background:var(--surface-2); padding:20px 22px; margin:10px 0; }
  .example h3{ font-family:var(--font-display); font-weight:700; font-size:17px; margin:0 0 3px; }
  .example .ref{ font-weight:700; font-size:12.5px; color:var(--clay-ink); margin:0 0 10px; }
  .example p{ font-family:var(--font-serif); font-size:15.5px; line-height:1.6; }
  .example em{ color:var(--ink-2); }
  .check{ display:flex; align-items:center; gap:10px; font-size:14.5px; color:var(--ink-2); padding:5px 0; }
  .check .b{ width:18px; height:18px; border-radius:5px; border:1.6px solid var(--line); flex-shrink:0; }
  .copyrow{ display:flex; justify-content:flex-end; margin-top:8px; }
  .copybtn{ font-family:var(--font-ui); font-weight:700; font-size:13px; padding:9px 14px; border-radius:11px; border:none; cursor:pointer; background:var(--clay); color:#fff; }
`;
const TMPL_CSS_PRINT = `
  @page{ size:A4; margin:14mm; }
  @media print{
    html,body{ background:#fff !important; }
    .no-print{ display:none !important; }
    .sheet{ width:100%; max-width:100%; box-shadow:none; border-radius:0; padding:0; }
    .sheet .scan{ background:#fff; }
    .doc{ width:100%; max-width:100%; box-shadow:none; border:none; border-radius:0; padding:0; }
    .block{ background:#fff; color:#1d1810; border:1px solid #ddd; }
    .block pre{ color:#2a2218; } .block .marker{ color:#8a6717; } .block .key{ color:#345c41; }
  }
`;

// SECURITY-AUDIT-2026-06-24 N5: also escape quotes. All current callers interpolate into element
// content (where unescaped quotes are safe), but pre-emptive quote-escaping means a future caller
// that drops a `${TMPL_ESC(x)}` into an attribute context (e.g. `<a title="...${x}...">`) doesn't
// silently introduce attribute-context XSS.
const TMPL_ESC = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

// ── the devotional fill-in block (verbatim from the design) ──
const DEVO_TPL =
'══════════════════ WEEK [N] — COPY FROM HERE ══════════════════\n\n' +
'Title: [Series Name] — Week [N]: [Week Theme]\n' +
'Summary: [One or two sentences describing this week. Shows in previews and feeds.]\n' +
'Tags: [topic], [topic], [topic]\n\n' +
'# [Series Name] — Week [N]: [Week Theme]\n\n' +
'*[Optional one-paragraph intro for the week, in italics. Delete if not needed.]*\n\n' +
'### Day [X] — [Short, vivid title]\n' +
'**[Scripture reference, e.g. Book 1:1–5]**\n\n' +
'[First paragraph. Make the point fast.]\n\n' +
'[Second paragraph. Land it. Don’t over-explain.]\n\n' +
'*[Closing line — a question, challenge, or one-line prayer.]*\n\n' +
'### Day [X] — [Short, vivid title]\n' +
'**[Scripture reference]**\n\n' +
'[Body.]\n\n' +
'*[Closing line.]*\n\n' +
'( …repeat the Day block for each day — 7 is the default; delete any you don’t need… )\n\n' +
'══════════════════ WEEK [N] — COPY TO HERE ══════════════════';

function devoTplHtml() {
  return TMPL_ESC(DEVO_TPL)
    .replace(/(══+[^\n]*══+)/g, '<span class="marker">$1</span>')
    .replace(/^(Title:|Summary:|Tags:)/gm, '<span class="key">$1</span>');
}

const HALO_SVG = (sz, color, spark) =>
  `<svg viewBox="0 0 100 100" style="width:${sz}px;height:${sz}px;color:${color}" aria-hidden="true">` +
  `<circle cx="50" cy="50" r="36" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-dasharray="57.4 18" transform="rotate(-90 50 50)"/>` +
  `<circle cx="50" cy="50" r="6.5" fill="${spark}"/></svg>`;

const TMPL_DEFAULT_TAG = 'A private, offline-first place to read and belong — no sign-up, no tracking.';

// ── the printable invite sheet markup ──
function inviteSheetHtml({ name, tag, url, qrSvg }) {
  const safeName = TMPL_ESC(name) || 'Your Church';
  const boxes = Array.from({ length: 12 }, (_, i) =>
    `<div class="box"><span class="n">${i + 1}</span><span class="line"></span></div>`).join('');
  return `
  <div class="sheet">
    <div class="eyebrow">${HALO_SVG(40, '#1d1810', 'var(--clay)')}<span>TRINITYONE</span></div>
    <h1>Join ${safeName}</h1>
    <p class="lede">${TMPL_ESC(tag || TMPL_DEFAULT_TAG)}</p>
    <div class="scan">
      <div class="lab">Scan this with your phone camera, or go to:</div>
      <div class="qr-box">${qrSvg || ''}</div>
      <div class="url">${TMPL_ESC(url)}</div>
    </div>
    <ol class="steps">
      <li>Open your phone camera and point it at the code above (or type the link into your browser).</li>
      <li>Tap <b>Add to Home Screen / Install</b> so TrinityOne lives on your phone and works offline.</li>
      <li>It opens already following <b>${safeName}</b>. Pick a display name, or stay anonymous.</li>
      <li>When asked, write down your <b>12-word recovery phrase</b> in the boxes below.</li>
    </ol>
    <div class="warn">
      <span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="10.5" width="14" height="9.5" rx="2.4"/><path d="M8 10.5V8a4 4 0 0 1 8 0v2.5"/></svg></span>
      <p>Keep your recovery phrase safe. It is the <b>only</b> way to restore your account on a new phone. No one — not even your church — can recover it for you. Don’t share it with anyone.</p>
    </div>
    <div class="rec-h">My 12-word recovery phrase</div>
    <div class="rec-sub">Write each word exactly as the app shows it, in order.</div>
    <div class="grid12">${boxes}</div>
    <div class="foot">${HALO_SVG(16, '#9a8f7c', 'var(--clay)')} TrinityOne · self-custodial fellowship</div>
  </div>`;
}

// ── the devotional contributor doc markup ──
function devoDocHtml() {
  return `
  <div class="doc">
    <div class="top"><span class="pill">${HALO_SVG(13, 'var(--clay-ink)', 'var(--clay-ink)')} Long-form · NIP-23</span></div>
    <h1>Devotional series — contributor template</h1>
    <p class="sub">A reusable template for writing a weekly devotional series and posting it to the church as long-form content. Copy the block, fill it in, post one week at a time. The app splits it into day-by-day reading for members.</p>
    <h2>How it works</h2>
    <ul>
      <li><b>One week = one block.</b> A full series is several weeks pasted one after another into a single <code>.md</code> file, then uploaded in Resources › Devotionals.</li>
      <li>Fill in the block between the <code>COPY FROM HERE / COPY TO HERE</code> markers.</li>
      <li>The <b>Title / Summary / Tags</b> lines describe the week.</li>
      <li><b>Markdown only.</b> Headings, <b>bold</b>, <em>italics</em> and rules render. Avoid tables and raw HTML.</li>
    </ul>
    <h2>House style</h2>
    <ul>
      <li><b>Short and punchy.</b> Each day is a few tight paragraphs, no padding.</li>
      <li><b>Plain, modern language.</b> Write like you talk.</li>
      <li><b>One Scripture per day</b>, bolded under the title. Reference and paraphrase rather than quoting long passages.</li>
      <li><b>End each day with a single italic closing line</b> — a question, a challenge, or a one-line prayer.</li>
      <li>Pick the number of days per week (7 default; fewer is fine).</li>
    </ul>
    <div class="rule">Fill-in block · copy for each week</div>
    <div class="block"><pre>${devoTplHtml()}</pre></div>
    <div class="copyrow no-print"><button class="copybtn" onclick="(function(b){navigator.clipboard&&navigator.clipboard.writeText(window.__DEVO_TPL__||'');b.textContent='Copied';setTimeout(function(){b.textContent='Copy template block'},1400);})(this)">Copy template block</button></div>
    <h2>Worked example · one day</h2>
    <div class="example">
      <h3>Day 1 — A word that means “unveiling”</h3>
      <p class="ref">Revelation 1:1–3</p>
      <p>The first word of the book is its key, and almost everyone loses it. <em>Apocalypse.</em> It does not mean disaster. It means unveiling — a hand pulling a curtain aside so you can finally see what was there all along.</p>
      <p>So forget the timelines you were handed. This book is not predicting your future. It is exposing your present.</p>
      <p><em>What would change if you believed God is unveiling now, not just later?</em></p>
    </div>
    <h2>Before you post</h2>
    <div class="check"><span class="b"></span> Title, Summary, Tags filled in</div>
    <div class="check"><span class="b"></span> One Scripture reference per day, bolded</div>
    <div class="check"><span class="b"></span> Each day ends with an italic closing line</div>
    <div class="check"><span class="b"></span> No tables or raw HTML</div>
    <div class="check"><span class="b"></span> Re-read once out loud — cut anything that drags</div>
  </div>`;
}

// open a clean popup containing the generated document (+ the brand tokens the CSS depends on)
function tmplOpen(innerHtml, title, { autoPrint = false, injectTpl = false } = {}) {
  const w = window.open('', '_blank', 'width=900,height=1100');
  if (!w) { alert('Allow pop-ups to generate this document.'); return; }
  const tplJs = injectTpl ? `<script>window.__DEVO_TPL__=${JSON.stringify(DEVO_TPL)};<\/script>` : '';
  const printJs = autoPrint ? `<script>setTimeout(function(){window.focus();window.print();},350);<\/script>` : '';
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${TMPL_ESC(title)}</title>
    <link rel="stylesheet" href="vendor/fonts/fonts.css"/>
    <link rel="stylesheet" href="brand.css"/>
    <style>:root{${TMPL_CSS_VARS}}
      html,body{margin:0;background:#efeae0;-webkit-print-color-adjust:exact;print-color-adjust:exact}
      body{padding:28px;font-family:var(--font-ui);color:var(--ink)}
      ${TMPL_CSS_BODY}${TMPL_CSS_PRINT}</style></head>
    <body>${innerHtml}${tplJs}${printJs}</body></html>`);
  w.document.close();
}

window.TrinityTemplates = {
  DEVO_TPL,
  // Print a polished A4 join invite (church QR + steps + blank recovery grid). Auto-opens print dialog.
  printInviteSheet({ name, tag, url, qrSvg } = {}) {
    tmplOpen(inviteSheetHtml({ name, tag, url, qrSvg }), (name || 'TrinityOne') + ' — invite', { autoPrint: true });
  },
  // Open the devotional contributor template (readable + copyable + printable). No auto-print.
  openDevoTemplate() {
    tmplOpen(devoDocHtml(), 'Devotional template', { injectTpl: true });
  },
};
