#!/usr/bin/env node
// Enrich catalog.json with sha256 + mirrors + Blossom servers + (optionally) magnet URIs.
// Run as part of scripts/release.sh, before deploy. Idempotent; safe to re-run.
//
// For every catalog entry with a local `url` (e.g. "modules/strongs-dict.json"):
//   - Compute sha256 of the file → write to entry.sha256.
//   - Set entry.mirrors[] to the same path on each canonical host (see MIRROR_HOSTS).
//   - Set entry.servers[] to <host>/blossom on each canonical host.
//   - If a matching .torrent was generated by scripts/build-torrents.sh, set entry.magnet.
//
// Import-type entries (kind:"import") and entries whose url is already an absolute URL are skipped.
import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('..', import.meta.url)));
const CATALOG = join(ROOT, 'catalog.json');
const TORRENTS = join(ROOT, 'modules', 'torrents');

// Candidate hosts that MAY serve /modules/<file> and /blossom/<sha256>. We probe each at build
// time and only advertise the ones that actually answer — so a relay not yet updated to the new
// gateway.mjs isn't listed as a Blossom server. (Engine still tries `mirrors[]` as a plain-HTTP
// fallback; that requires only static-file hosting, which every gateway does.)
const CANDIDATE_HOSTS = [
  'https://trinityone.tailbeaac0.ts.net',
  'https://trinityone-master-01.tailbeaac0.ts.net',
  'https://trinityone-nas.tailbeaac0.ts.net',
];

async function probeHosts() {
  const mirrorHosts = [], blossomHosts = [];
  for (const host of CANDIDATE_HOSTS) {
    let okHttp = false, okBlossom = false;
    try { const r = await fetch(host + '/catalog.json', { signal: AbortSignal.timeout(3000) }); okHttp = r.ok; } catch {}
    try { const r = await fetch(host + '/blossom/list', { signal: AbortSignal.timeout(3000) }); okBlossom = r.ok; } catch {}
    if (okHttp) mirrorHosts.push(host);
    if (okBlossom) blossomHosts.push(host);
    console.log(`  ${host}  static=${okHttp ? 'yes' : 'no '}  blossom=${okBlossom ? 'yes' : 'no '}`);
  }
  return { mirrorHosts, blossomHosts };
}

function sha256File(p) {
  const h = createHash('sha256'); h.update(readFileSync(p)); return h.digest('hex');
}
function size(p) { return statSync(p).size; }
function isLocalUrl(u) { return u && !/^https?:/i.test(u); }

const catalog = JSON.parse(readFileSync(CATALOG, 'utf8'));
let touched = 0, skipped = 0, missing = [];

console.log('probing candidate hosts…');
const { mirrorHosts, blossomHosts } = await probeHosts();

for (const cat of catalog.categories || []) {
  for (const item of cat.items || []) {
    if (item.kind === 'import') { skipped++; continue; }
    if (!isLocalUrl(item.url)) { skipped++; continue; }
    const abs = join(ROOT, item.url);
    if (!existsSync(abs)) { missing.push(item.url); continue; }

    const hash = sha256File(abs);
    item.sha256 = hash;
    item.bytes = size(abs);
    item.mirrors = mirrorHosts.map(h => h + '/' + item.url);
    item.servers = blossomHosts.map(h => h + '/blossom');

    // Optional torrent layer: if a sibling .torrent exists, derive the magnet URI for it.
    const torrent = join(TORRENTS, item.url.replace(/^modules\//, '') + '.torrent');
    if (existsSync(torrent)) {
      // Read the .torrent file's info-hash. mktorrent writes BEP-3 bencoded; computing the
      // info-hash properly needs bencode parsing. To stay dep-free, we fall back to publishing
      // the .torrent's location and let clients grab it; the magnet URI gets set by
      // scripts/build-torrents.sh which already knows the hash at generation time.
      const magnetSidecar = torrent + '.magnet';
      if (existsSync(magnetSidecar)) {
        item.magnet = readFileSync(magnetSidecar, 'utf8').trim();
      }
    }

    touched++;
  }
}

// Bump the catalog version every build so a member's client can tell when a fresh event arrives.
catalog.version = (catalog.version || 0) + 1;
catalog.builtAt = Math.floor(Date.now() / 1000);

writeFileSync(CATALOG, JSON.stringify(catalog, null, 2) + '\n');

console.log(`catalog v${catalog.version} — ${touched} entries enriched, ${skipped} skipped (import/absolute)`);
if (missing.length) {
  console.warn(`⚠  ${missing.length} entries reference a missing local file (not hashed):`);
  for (const m of missing) console.warn('   -', m);
  process.exitCode = 1;   // surface this in CI/release.sh
}
