#!/usr/bin/env bash
# Build the standalone Steward APK (trinityone-steward.apk): the steward console
# (steward.html + stew-*.jsx) wrapped as its OWN Android app (com.trinityone.steward), so a steward
# can create + manage a church on a phone, talking straight to the relays — a host-independent
# fallback if the web console is blocked. Re-uses the shared android/ project via a temporary
# applicationId / app-name / webDir swap, ALWAYS reverted on exit (the member project is restored).
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"
WWW="$ROOT/www"
GRADLE="android/app/build.gradle"
STRINGS="android/app/src/main/res/values/strings.xml"
RES="android/app/src/main/res"
DENS="mdpi hdpi xhdpi xxhdpi xxxhdpi"
ICON_BAK="$(mktemp -d)"

# whatever happens, put the member project back (app id, name, icon, and the member www/)
restore() {
  sed -i 's/applicationId "com.trinityone.steward"/applicationId "com.trinityone.app"/' "$GRADLE" 2>/dev/null || true
  sed -i 's#<string name="app_name">TrinityOne Steward</string>#<string name="app_name">TrinityOne</string>#' "$STRINGS" 2>/dev/null || true
  for d in $DENS; do cp "$ICON_BAK/mipmap-$d/"*.png "$RES/mipmap-$d/" 2>/dev/null || true; done
  rm -rf "$ICON_BAK"
  echo "restoring member www/ + project…"
  bash scripts/sync-web.sh >/dev/null 2>&1 || true
}
trap restore EXIT

source scripts/android-env.sh

# swap to the steward (midnight + keeper-ring) launcher icon — same adaptive XML, swapped mipmap PNGs.
# Back up the member icons first (android/ is gitignored = disk-only) and restore them on exit.
# Steward icons are generated by: node scripts/make-icons.mjs  (committed under assets/steward-icons/).
if [ -d assets/steward-icons ]; then
  echo "swapping in the steward icon…"
  for d in $DENS; do
    mkdir -p "$ICON_BAK/mipmap-$d"
    cp "$RES/mipmap-$d/"ic_launcher*.png "$ICON_BAK/mipmap-$d/" 2>/dev/null || true
    cp assets/steward-icons/mipmap-$d/*.png "$RES/mipmap-$d/"
  done
fi

# 1. steward webDir — only what steward.html references; steward.html becomes index.html
echo "building steward webDir…"
rm -rf "$WWW"; mkdir -p "$WWW/vendor"
cp steward.html "$WWW/index.html"
cp brand.css "$WWW/"
mkdir -p "$WWW/app"
cp app/icons.jsx app/stew-modal.jsx app/recur.jsx app/stew-data.jsx app/stew-console.jsx app/stew-schedule.jsx app/stew-templates.jsx \
   app/stew-dashboard.jsx app/stew-finance.jsx app/stew-manna.jsx app/stew-meals.jsx app/stew-relay.jsx app/stew-extension.jsx app/stew-phone.jsx app/stew-custody.jsx \
   app/backup.jsx app/steward-root.jsx "$WWW/app/"
cp -r vendor/fonts "$WWW/vendor/"
cp vendor/react.production.min.js vendor/react-dom.production.min.js vendor/steward.js vendor/finance-ledger.js vendor/steward-manna.js vendor/steward-meals.js vendor/jsqr.js vendor/jspdf.umd.min.js "$WWW/vendor/"

# pre-transpile JSX -> JS (runtime Babel is unreliable in the Capacitor webview)
echo "transpiling steward JSX -> JS…"
for f in "$WWW"/app/*.jsx; do
  base="$(basename "$f" .jsx)"
  ./node_modules/.bin/esbuild "$f" --jsx=transform --log-level=error --outfile="$WWW/app/$base.js"
  rm "$f"
done
sed -i -e '/babel\.min\.js/d' -e 's#<script type="text/babel" src="\([^"]*\)\.jsx">#<script src="\1.js">#g' "$WWW/index.html"

# 2. swap to the Steward app identity (separate install from the member app)
sed -i 's/applicationId "com.trinityone.app"/applicationId "com.trinityone.steward"/' "$GRADLE"
sed -i 's#<string name="app_name">TrinityOne</string>#<string name="app_name">TrinityOne Steward</string>#' "$STRINGS"

# 3. copy webDir into the native project + build
# SECURITY-AUDIT-2026-07-20 C3: this built assembleDebug, so the STEWARD apk — the one holding the church
# signing key — shipped android:debuggable=true and was signed with the ANDROID DEBUG CERTIFICATE
# (CN=Android Debug) rather than the release key. debuggable=true enables `adb shell run-as` on ordinary
# unrooted phones: ~30s of USB access to an unlocked steward device reads the app's private storage, where
# the PIN-encrypted church key lives — reducing key theft to an offline PIN brute-force. It also let anyone
# holding ~/.android/debug.keystore (regenerated silently if deleted) forge a steward update.
npx cap copy android
[ -f android/app/keystore.properties ] || { echo "ERROR: android/app/keystore.properties missing — refusing to build an unsigned/debug-signed steward APK" >&2; exit 1; }
( cd android && ./gradlew assembleRelease -q )
cp android/app/build/outputs/apk/release/app-release.apk trinityone-steward.apk
# Fail loudly rather than ever shipping a debuggable console again.
if command -v aapt2 >/dev/null 2>&1 && aapt2 dump badging trinityone-steward.apk 2>/dev/null | grep -q "application-debuggable"; then
  echo "ERROR: trinityone-steward.apk is DEBUGGABLE — refusing to ship it" >&2; rm -f trinityone-steward.apk; exit 1
fi
echo "→ trinityone-steward.apk ($(du -h trinityone-steward.apk | cut -f1))"
# restore() runs on EXIT
