#!/usr/bin/env bash
# Build the standalone Steward APK (trinityone-steward.apk): the steward console
# (steward.html + stew-*.jsx) wrapped as its OWN Android app (com.trinityone.steward), so a steward
# can create + manage a church on a phone, talking straight to the relays — a host-independent
# fallback if the web console is blocked. Re-uses the shared android/ project via a temporary
# applicationId / app-name / webDir swap, ALWAYS reverted on exit (the member project is restored).
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"
WWW="$ROOT/www"
GRADLE="android/app/build.gradle"
STRINGS="android/app/src/main/res/values/strings.xml"
RES="android/app/src/main/res"
DENS="mdpi hdpi xhdpi xxhdpi xxxhdpi"
ICON_BAK="$(mktemp -d)"

# whatever happens, put the member project back (app id, name, icon, and the member www/)
restore() {
  sed -i 's/applicationId "com.trinityone.steward"/applicationId "com.trinityone.app"/' "$GRADLE" 2>/dev/null || true
  sed -i 's#<string name="app_name">TrinityOne Steward</string>#<string name="app_name">TrinityOne</string>#' "$STRINGS" 2>/dev/null || true
  for d in $DENS; do cp "$ICON_BAK/mipmap-$d/"*.png "$RES/mipmap-$d/" 2>/dev/null || true; done
  rm -rf "$ICON_BAK"
  echo "restoring member www/ + project…"
  bash scripts/sync-web.sh >/dev/null 2>&1 || true
}
trap restore EXIT

source scripts/android-env.sh

# swap to the steward (midnight + keeper-ring) launcher icon — same adaptive XML, swapped mipmap PNGs.
# Back up the member icons first (android/ is gitignored = disk-only) and restore them on exit.
# Steward icons are generated by: node scripts/make-icons.mjs  (committed under assets/steward-icons/).
if [ -d assets/steward-icons ]; then
  echo "swapping in the steward icon…"
  for d in $DENS; do
    mkdir -p "$ICON_BAK/mipmap-$d"
    cp "$RES/mipmap-$d/"ic_launcher*.png "$ICON_BAK/mipmap-$d/" 2>/dev/null || true
    cp assets/steward-icons/mipmap-$d/*.png "$RES/mipmap-$d/"
  done
fi

# 1. steward webDir — only what steward.html references; steward.html becomes index.html
echo "building steward webDir…"
rm -rf "$WWW"; mkdir -p "$WWW/vendor"
cp steward.html "$WWW/index.html"
cp -r vendor/fonts "$WWW/vendor/"

# DERIVED FROM steward.html, NOT HAND-LISTED — because the hand list drifted, and shipped a dead app.
#
# This used to be an explicit `cp app/icons.jsx app/stew-modal.jsx …` naming every file. On 2026-08-17
# `app/error-boundary.jsx` was added to steward.html and not to that list, so the APK shipped without it,
# steward-root.js threw `ReferenceError: TrinityErrorBoundary is not defined` at mount, React never rendered,
# and the console sat on "Opening your console… Getting your church ready" for ever. Two days and 31 commits
# went by unnoticed: every console test runs HEADLESS against the repo root, where every file exists, so only
# the packaged app was broken and only a phone could show it. (The commit that caused it was called "a render
# crash stops being a silent white screen".) vendor/recovery.js, sw-register.js and the icons were missing
# too — the restore path and the launcher art.
#
# So the page is now the source of truth: copy every local file steward.html references, and FAIL if one is
# missing rather than shipping an app that dies at mount.
echo "collecting the files steward.html references…"
REFS=$(grep -oE '(href|src)="[^"]+"' steward.html | sed 's/.*="//;s/"//' | grep -vE '^https?:|^#|^data:' | sort -u)
for f in $REFS; do
  # babel is deliberately dropped: the JSX below is pre-transpiled, and runtime Babel is unreliable in the
  # Capacitor webview (it is also what the strict, eval-free CSP exists to allow us to turn off).
  [ "$f" = "vendor/babel.min.js" ] && continue
  [ "$f" = "vendor/fonts/fonts.css" ] && continue   # came with vendor/fonts above
  if [ ! -f "$f" ]; then echo "✖ steward.html references $f, which does not exist — fix the page or add the file" >&2; exit 1; fi
  mkdir -p "$WWW/$(dirname "$f")"
  cp "$f" "$WWW/$f"
done

# pre-transpile JSX -> JS (runtime Babel is unreliable in the Capacitor webview)
echo "transpiling steward JSX -> JS…"
for f in "$WWW"/app/*.jsx; do
  base="$(basename "$f" .jsx)"
  ./node_modules/.bin/esbuild "$f" --jsx=transform --log-level=error --outfile="$WWW/app/$base.js"
  rm "$f"
done
sed -i -e '/babel\.min\.js/d' -e 's#<script type="text/babel" src="\([^"]*\)\.jsx">#<script src="\1.js">#g' "$WWW/index.html"

# 2. swap to the Steward app identity (separate install from the member app)
sed -i 's/applicationId "com.trinityone.app"/applicationId "com.trinityone.steward"/' "$GRADLE"
sed -i 's#<string name="app_name">TrinityOne</string>#<string name="app_name">TrinityOne Steward</string>#' "$STRINGS"

# 3. copy webDir into the native project + build
#
# ⚠ PILOT-DEFERRED: DEBUG-signed on purpose (owner's call, 2026-07-22). 8f5090e switched this to
# assembleRelease (release cert, no android:debuggable) as a SECURITY fix — correct for go-live, but it was
# part of the go-live hardening the owner had explicitly deferred until pilot start, and it slipped through
# the same-batch revert that put webContentsDebuggingEnabled back ON (9c74d61). Release-signing mid-pilot-prep
# breaks the test phone's in-place update path (a different key can't upgrade the installed app), so this is
# reverted to the debug cert the phone already trusts. No real congregation is on anything yet, so the
# debug-cert / debuggable blast radius is zero — which is exactly why it was deferred.
#
# ‼ BEFORE ANY REAL GO-LIVE: build with TRINITY_DEBUG=0 (handled just below — disables WebView debugging on
#   the steward APK too) AND switch back to the release build below. It is the correct shipping posture:
#     [ -f android/app/keystore.properties ] || { echo "ERROR: keystore.properties missing" >&2; exit 1; }
#     ( cd android && ./gradlew assembleRelease -q )
#     cp android/app/build/outputs/apk/release/app-release.apk trinityone-steward.apk
#     aapt2 dump badging trinityone-steward.apk | grep -q application-debuggable && { echo "DEBUGGABLE — refusing"; exit 1; }
#   The 8f5090e security rationale (debuggable=true → adb run-as reads the PIN-encrypted church key in ~30s;
#   a silently-regenerated debug key can forge steward updates) is REAL and applies the moment anyone real is on it.
npx cap copy android
# Honour the same TRINITY_DEBUG=0 go-live switch as sync-web.sh (member APK). `npx cap copy` just re-copied
# capacitor.config.json with webContentsDebuggingEnabled=true (the committed pilot value), and this build
# never applied the switch — so a go-live run that disabled WebView debugging on the MEMBER app still shipped
# the STEWARD app (which holds the church key) debuggable. Unset = leave it ON (owner's pilot decision);
# TRINITY_DEBUG=0 = force it off here too, so one switch covers both apps.
ASSETS_CFG="android/app/src/main/assets/capacitor.config.json"
if [ -f "$ASSETS_CFG" ]; then
  if [ "${TRINITY_DEBUG:-}" = "0" ]; then
    node -e 'const f=process.argv[1],c=JSON.parse(require("fs").readFileSync(f,"utf8"));(c.android=c.android||{}).webContentsDebuggingEnabled=false;require("fs").writeFileSync(f,JSON.stringify(c,null,2)+"\n")' "$ASSETS_CFG"
    echo "✔ TRINITY_DEBUG=0 — WebView remote debugging DISABLED in the steward APK (go-live posture)."
  elif grep -q '"webContentsDebuggingEnabled": *true' "$ASSETS_CFG"; then
    echo "⚠ Steward APK WebView remote debugging is ON (pilot). Ship with TRINITY_DEBUG=0 at go-live."
  fi
fi
( cd android && ./gradlew assembleDebug -q )
cp android/app/build/outputs/apk/debug/app-debug.apk trinityone-steward.apk
echo "→ trinityone-steward.apk ($(du -h trinityone-steward.apk | cut -f1))  [DEBUG-signed — pilot-deferred, see note above]"
# restore() runs on EXIT
