// THE PUBLIC SITE MUST BE REACHABLE AND WHOLE. Run: node --test scripts/site-links.test.mjs
//
// MARKETING-AUDIT-2026-08-05. The site had grown to 17 pages of which FIVE were unreachable — nothing on the
// site linked them — and those five held 52% of all its prose. The two largest bodies of text on the whole
// site were both orphans. That is not a copy problem, it is a structural one: there were three different navs
// (a 7-link nav on five pages, a 2-link nav on two, and no nav at all on nine), so a page could be added, or
// silently lose its last inbound link, and nobody would notice.
//
// It had already happened invisibly once: how-trinityone-stays-up.html:266 RECORDED that install-anywhere was
// "linked from welcome.html footer". It was not. The document that owned the resilience story asserted the
// link shipped, so nobody re-checked — and both pages sat unreachable, one of them publishing the live relay
// hosts and their tailnet names.
//
// So this asserts the two properties a reader depends on, by walking the real files rather than by listing
// pages I happened to look at:
//   1. every internal link resolves to a file that exists
//   2. every served page is reachable from the home page
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync, readdirSync } from 'node:fs';

const ROOT = new URL('..', import.meta.url).pathname;
const read = (f) => readFileSync(ROOT + f, 'utf8');

// The app shells are not marketing pages: index.html/steward.html are the app itself, and they are reached by
// domain (app.trinityone.church), not by a link from the brochure.
const APP_SHELLS = new Set(['index.html', 'steward.html']);
// apks.html is generated by build-apk-index.sh, gitignored, and served only over Tailscale to the operator.
const NOT_TRACKED = new Set(['apks.html']);
// ENTRY POINTS: pages people ARRIVE on from outside the site — an invite URL, a QR on a printed slip — rather
// than browse to. join.html renders standalone with no code ("You're invited… Open TrinityOne now"), and
// linking it from the nav would drop a browsing reader onto an invitation to nothing. Being unreferenced is
// correct for these and only these. Keep this set tiny and justified: it is the exemption that could quietly
// re-admit the orphan problem, so a page belongs here only if arriving from outside is its ONLY sane route.
const ENTRY_POINTS = new Set(['join.html']);

const pages = readdirSync(ROOT).filter(f => f.endsWith('.html') && !APP_SHELLS.has(f) && !NOT_TRACKED.has(f));

// strip comments so a link quoted inside an HTML comment (e.g. an audit note naming a deleted page) is not
// mistaken for a live one — the same trap that let a comment satisfy an ordering assertion elsewhere today.
const live = (s) => s.replace(/<!--[\s\S]*?-->/g, '');
const linksIn = (f) => [...live(read(f)).matchAll(/(?:href|src)="([^"#?][^"]*)"/g)]
  .map(m => m[1])
  .filter(u => !/^(https?:|mailto:|tel:|data:|\/\/)/.test(u))
  .map(u => u.replace(/[#?].*$/, '').replace(/^\.\//, ''))
  .filter(Boolean);

test('every internal link points at a file that exists', () => {
  const broken = [];
  for (const p of pages) {
    for (const u of linksIn(p)) {
      const target = u.startsWith('/') ? u.slice(1) : u;
      if (!target || target.endsWith('/')) continue;              // directory / root links
      if (NOT_TRACKED.has(target)) continue;
      if (!existsSync(ROOT + target)) broken.push(`${p} → ${u}`);
    }
  }
  assert.deepEqual(broken, [],
    'these links 404. A dead link on the brochure is worse than a missing page: the reader believes there ' +
    'is something there and concludes the product is broken.\n  ' + broken.join('\n  '));
});

// THE ORPHAN CHECK — the one that would have caught the 52%.
test('every served page is reachable from the home page', () => {
  const home = 'welcome.html';
  assert.ok(existsSync(ROOT + home), 'welcome.html is the home page — re-anchor if that changed');
  // `/` resolves to welcome.html on the deployed site.
  const seen = new Set([home]);
  const queue = [home];
  while (queue.length) {
    const cur = queue.shift();
    for (const u of linksIn(cur)) {
      let t = u.startsWith('/') ? u.slice(1) : u;
      if (t === '' || t.endsWith('/')) t = home;
      if (!t.endsWith('.html') || seen.has(t) || !existsSync(ROOT + t)) continue;
      seen.add(t); queue.push(t);
    }
  }
  const orphans = pages.filter(p => !seen.has(p) && !ENTRY_POINTS.has(p));
  assert.deepEqual(orphans, [],
    'these pages are served but nothing links to them. Five pages in this state held 52% of the site\'s ' +
    'prose, including one publishing the live relay hosts. If a page is deliberately out of the nav, it ' +
    'still needs SOME inbound link — or it should not be served.\n  ' + orphans.join('\n  '));
});

// The audit found three "📸 Screenshot placeholder — replace this box with a real screenshot" boxes served
// publicly on verify-a-child.html since 2026-06-25. That page is gone; this stops the next one.
test('no page serves an unfinished placeholder', () => {
  const bad = pages.filter(p => /placeholder|TODO|FIXME|lorem ipsum/i.test(live(read(p))));
  assert.deepEqual(bad, [],
    'these pages contain a placeholder that the public can read: ' + bad.join(', '));
});

// Every surviving page must offer a way onward. The 2-link navs are how features.html and
// welcome-churches.html became dead ends a reader could land on from search.
test('every page in the nav can navigate onward', () => {
  const inNav = ['welcome.html', 'why.html', 'features.html', 'downloads.html', 'welcome-churches.html', 'help.html'];
  for (const p of inNav) {
    const nav = live(read(p)).match(/<nav class="top">[\s\S]*?<\/nav>/);
    assert.ok(nav, `${p} has no top nav — that is how a page becomes a dead end`);
    const hrefs = [...nav[0].matchAll(/href="([^"]+)"/g)].map(m => m[1]).filter(h => h.endsWith('.html'));
    assert.ok(hrefs.length >= 5,
      `${p}'s nav offers only ${hrefs.length} page link(s). A reader landing here from search has almost ` +
      `nowhere to go, which is exactly how this site accumulated five orphans.`);
  }
});

// THE INVITE MUST REACH THE APP, ON EVERY HOST THAT SERVES IT. Journey audit 2026-08-05.
//
// Measured live: both domains serve the whole repo and differ in one place — trinityone.church/ is
// welcome.html (the brochure) while app.trinityone.church/ is the app. joinUrl() builds the invite from
// location.origin whenever it is public, and trinityone.church/steward.html serves the console — so a steward
// working from the marketing domain hands out an invite whose "Open TrinityOne now" button pointed at
// `/?follow=…` and landed the member on the sales page, church silently dropped. The page said "Join <church>"
// and "Hi, <name>" first, so it looked like it had worked.
test('the join landing sends people to the app, not to whatever "/" happens to be', () => {
  const js = readFileSync(ROOT + 'join.js', 'utf8').replace(/\/\/[^\n]*/g, '');
  assert.doesNotMatch(js, /var app = '\/\?follow=/,
    'join.js opens "/?follow=…". On the marketing domain "/" is welcome.html, so the invite drops the member ' +
    'on the brochure with no error and no church.');
  assert.match(js, /var app = 'index\.html\?follow=/,
    'the join landing must target index.html — the one path that is the app on every host that serves this ' +
    'page (marketing, app, and any church\'s own relay)');
});
